// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActionLogin(arg1) {
  return window['go']['auth']['App']['ActionLogin'](arg1);
}

export function ActionLogout(arg1) {
  return window['go']['auth']['App']['ActionLogout'](arg1);
}
