// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActionDelete(arg1) {
  return window['go']['student']['App']['ActionDelete'](arg1);
}

export function ActionForm(arg1) {
  return window['go']['student']['App']['ActionForm'](arg1);
}

export function Student(arg1) {
  return window['go']['student']['App']['Student'](arg1);
}

export function Students() {
  return window['go']['student']['App']['Students']();
}
