// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {student} from '../models';

export function ActionDelete(arg1:number):Promise<string>;

export function ActionForm(arg1:student.Student):Promise<string>;

export function Student(arg1:number):Promise<string>;

export function Students():Promise<string>;
