// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActionSync(arg1) {
  return window['go']['sync']['App']['ActionSync'](arg1);
}

export function Sync(arg1) {
  return window['go']['sync']['App']['Sync'](arg1);
}

export function Syncs() {
  return window['go']['sync']['App']['Syncs']();
}
