// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActionSync(arg1:string):Promise<string>;

export function Sync(arg1:number):Promise<string>;

export function Syncs():Promise<string>;
